from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('master/user/', views.user_index, name='user-index'),
    path('master/user/add/', views.user_add, name='user-add'),
    path('master/user/view/<str:_id>/', views.user_view, name='user-view'),
    path('master/user/update/<str:_id>/',
         views.user_update, name='user-update'),
    path('master/user/delete/<str:_id>/',
         views.user_delete, name='user-delete'),
    path('master/user/remove-signature/<str:_id>/',
         views.remove_signature, name='remove-signature'),
    path('master/user/change-password/',
         views.change_password, name='change-password'),
    path('master/user/set-password/<str:_id>/',
         views.set_password, name='set-password'),
    path('master/user-area/view/<str:_id>/',
         views.user_area_view, name='user-area-view'),
    path('master/distributor/', views.distributor_index, name='distributor-index'),
    path('master/distributor/add/', views.distributor_add, name='distributor-add'),
    path('master/distributor/view/<str:_id>/',
         views.distributor_view, name='distributor-view'),
    path('master/distributor/update/<str:_id>/',
         views.distributor_update, name='distributor-update'),
    path('master/distributor/delete/<str:_id>/',
         views.distributor_delete, name='distributor-delete'),
    path('master/area-sales/', views.area_sales_index, name='area-sales-index'),
    path('master/area-sales/add/', views.area_sales_add, name='area-sales-add'),
    path('master/area-sales/view/<str:_id>/',
         views.area_sales_view, name='area-sales-view'),
    path('master/area-sales/update/<str:_id>/',
         views.area_sales_update, name='area-sales-update'),
    path('master/area-sales/delete/<str:_id>/',
         views.area_sales_delete, name='area-sales-delete'),
    path('master/position/', views.position_index, name='position-index'),
    path('master/position/add/', views.position_add, name='position-add'),
    path('master/position/view/<str:_id>/',
         views.position_view, name='position-view'),
    path('master/position/update/<str:_id>/',
         views.position_update, name='position-update'),
    path('master/position/delete/<str:_id>/',
         views.position_delete, name='position-delete'),
    path('master/menu/', views.menu_index, name='menu-index'),
    path('master/menu/add/', views.menu_add, name='menu-add'),
    path('master/menu/view/<str:_id>/', views.menu_view, name='menu-view'),
    path('master/menu/update/<str:_id>/',
         views.menu_update, name='menu-update'),
    path('master/menu/delete/<str:_id>/',
         views.menu_delete, name='menu-delete'),
    path('master/auth/update/<str:_id>/<str:_menu>/',
         views.auth_update, name='auth-update'),
    path('master/auth/delete/<str:_id>/<str:_menu>/',
         views.auth_delete, name='auth-delete'),
    path('master/area-user/delete/<str:_id>/<str:_area>/',
         views.area_user_delete, name='area-user-delete'),
    path('master/room/', views.room_index, name='room-index'),
    path('master/room/add/', views.room_add, name='room-add'),
    path('master/room/view/<str:_id>/',
         views.room_view, name='room-view'),
    path('master/room/update/<str:_id>/',
         views.room_update, name='room-update'),
    path('master/room/delete/<str:_id>/',
         views.room_delete, name='room-delete'),
    path('master/task/update/<str:_id>/', views.task_update,
         name='task-update'),
    path('master/task/delete/<str:_id>/',
         views.task_delete, name='task-delete'),
    path('master/equipment/', views.equipment_index, name='equipment-index'),
    path('master/equipment/add/', views.equipment_add, name='equipment-add'),
    path('master/equipment/view/<str:_id>/',
         views.equipment_view, name='equipment-view'),
    path('master/equipment/update/<str:_id>/', views.equipment_update,
         name='equipment-update'),
    path('master/equipment/delete/<str:_id>/', views.equipment_delete,
         name='equipment-delete'),
    path('master/category/', views.category_index, name='category-index'),
    path('master/category/add/', views.category_add, name='category-add'),
    path('master/category/view/<str:_id>/',
         views.category_view, name='category-view'),
    path('master/category/update/<str:_id>/', views.category_update,
         name='category-update'),
    path('master/category/delete/<str:_id>/',
         views.category_delete, name='category-delete'),
    path('master/package/', views.package_index, name='package-index'),
    path('master/package/add/', views.package_add, name='package-add'),
    path('master/package/update/<str:_id>/',
         views.package_update, name='package-update'),
    path('master/package/delete/<str:_id>/',
         views.package_delete, name='package-delete'),
    path('master/package-addon/update/<str:_id>/<str:_eq>/',
         views.package_addon_update, name='package-addon-update'),
    path('master/package-bag/delete/<str:_id>/<str:_eq>/',
         views.package_bag_delete, name='package-bag-delete'),
    path('master/package-box/delete/<str:_id>/<str:_eq>/',
         views.package_box_delete, name='package-box-delete'),
    path('master/package-addon/delete/<str:_id>/<str:_eq>/',
         views.package_addon_delete, name='package-addon-delete'),
    path('master/channel/', views.channel_index, name='channel-index'),
    path('master/channel/add/', views.channel_add, name='channel-add'),
    path('master/channel/view/<str:_id>/',
         views.channel_view, name='channel-view'),
    path('master/channel/update/<str:_id>/',
         views.channel_update, name='channel-update'),
    path('master/channel/delete/<str:_id>/',
         views.channel_delete, name='channel-delete'),
    path('master/closing-period/', views.closing_index, name='closing-index'),
    path('master/closing-period/add/', views.closing_add, name='closing-add'),
    path('master/closing-period/view/<str:_id>/',
         views.closing_view, name='closing-view'),
    path('master/closing-period/update/<str:_id>/', views.closing_update,
         name='closing-update'),
    path('master/closing-period/delete/<str:_id>/', views.closing_delete,
         name='closing-delete'),
    path('master/division/', views.division_index, name='division-index'),
    path('master/division/add/', views.division_add, name='division-add'),
    path('master/division/view/<str:_id>/',
         views.division_view, name='division-view'),
    path('master/division/update/<str:_id>/',
         views.division_update, name='division-update'),
    path('master/division/delete/<str:_id>/',
         views.division_delete, name='division-delete'),
    path('claim/<str:_tab>/', views.claim_index, name='claim-index'),
    path('claim/add/<str:_area>/<str:_distributor>/<path:_program>/',
         views.claim_add, name='claim-add'),
    path('claim/view/<str:_tab>/<path:_id>/',
         views.claim_view, name='claim-view'),
    path('claim/update/<str:_tab>/<path:_id>/',
         views.claim_update, name='claim-update'),
    path('claim/delete/<str:_tab>/<path:_id>/',
         views.claim_delete, name='claim-delete'),
    path('claim_release/', views.claim_release_index,
         name='claim-release-index'),
    path('claim_release/view/<path:_id>/<int:_is_revise>/',
         views.claim_release_view, name='claim-release-view'),
    path('claim_release/update/<path:_id>/',
         views.claim_release_update, name='claim-release-update'),
    path('claim_release/approve/<path:_id>/',
         views.claim_release_approve, name='claim-release-approve'),
    path('claim_release/return/<path:_id>/',
         views.claim_release_return, name='claim-release-return'),
    path('claim_release/reject/<path:_id>/',
         views.claim_release_reject, name='claim-release-reject'),
    path('claim_archive/', views.claim_archive_index, name='claim-archive-index'),
    path('matrix/claim/', views.claim_matrix_index,
         name='claim-matrix-index'),
    path('matrix/claim/view/<str:_id>/<str:_channel>/',
         views.claim_matrix_view, name='claim-matrix-view'),
    path('matrix/claim/update/<str:_id>/<str:_channel>/<str:_approver>/',
         views.claim_matrix_update, name='claim-matrix-update'),
    path('matrix/claim/delete/<str:_id>/<str:_channel>/<str:_arg>/',
         views.claim_matrix_delete, name='claim-matrix-delete'),
    path('claim_print/<path:_id>/',
         views.claim_print, name='claim-print'),
    path('master/region/', views.region_index, name='region-index'),
    path('master/region/add/', views.region_add, name='region-add'),
    path('master/region/view/<str:_id>/',
         views.region_view, name='region-view'),
    path('master/region/update/<str:_id>/',
         views.region_update, name='region-update'),
    path('master/region/delete/<str:_id>/',
         views.region_delete, name='region-delete'),
    path('master/region-detail/delete/<str:_id>/<str:_room>/',
         views.region_detail_delete, name='region-detail-delete'),
    path('master/customer/', views.customer_index, name='customer-index'),
    path('master/customer/add/', views.customer_add, name='customer-add'),
    path('master/customer/view/<str:_id>/<str:_msg>/',
         views.customer_view, name='customer-view'),
    path('master/customer/update/<str:_id>/',
         views.customer_update, name='customer-update'),
    path('master/customer/delete/<str:_id>/',
         views.customer_delete, name='customer-delete'),
    path('master/customer-detail/update/<str:_id>/<str:_child>/',
         views.customer_detail_update, name='customer-detail-update'),
    path('master/customer-detail/delete/<str:_id>/',
         views.customer_detail_delete, name='customer-detail-delete'),
    path('order/new/<path:_reg>/', views.order_add, name='order-add'),
    path('order/update/<path:_id>/', views.order_update, name='order-update'),
    path('order/child/add/<path:_id>/<int:_add>/',
         views.order_child_add, name='order-child-add'),
    path('order/child/update/<path:_id>/<int:_child>/<int:_add>/',
         views.order_child_update, name='order-child-update'),
    path('order/child/cs/update/<path:_id>/<str:_child>/',
         views.order_child_cs_update, name='order-child-cs-update'),
    path('order/child/delete/<path:_id>/<int:_child>/',
         views.order_child_delete, name='order-child-delete'),
    path('order/child/cs/delete/<path:_id>/<int:_child>/',
         views.order_child_cs_delete, name='order-child-cs-delete'),
    path('order/submit/<path:_id>/', views.order_submit, name='order-submit'),
    path('form/', views.form_index, name='form-index'),
    path('checklist/', views.checklist_index, name='checklist-index'),
    path('checklist/view/<str:_id>/', views.checklist_view, name='checklist-view'),
    path('attendance/clock-in/', views.clock_in, name='clock-in'),
    path('submit-attendance/', views.submit_attendance, name='submit-attendance'),
    path('attendance/clock-in-success/',
         views.clock_in_success, name='clock-in-success'),
    path('attendance/clock-out/', views.clock_out, name='clock-out'),
    path('attendance/clock-out-success/',
         views.clock_out_success, name='clock-out-success'),
    path('checklist/remove-attachment/<str:_id>/',
         views.remove_attachment, name='remove-attachment'),
    path('report/attendance/<str:_from_date>/<str:_to_date>/<str:_user>/',
         views.attendance_report, name='attendance-report'),
    path('report/urgent/', views.report_urgent_index, name='report-urgent-index'),
    path('report/urgent-detail/<int:_id>/', views.report_urgent_detail,
         name='report-urgent-detail'),
    path('report/marbot/export/<str:_from_date>/<str:_to_date>/<str:_room>/',
         views.report_marbot_toxl, name='report-marbot-toxl'),
    path('order/', views.order_index, name='order-index'),
    path('order/cancel/<path:_id>/', views.order_cancel, name='order-cancel'),
    path('order/confirmed/<path:_id>/',
         views.order_confirmed, name='order-confirmed'),
    path('order/cs/child/add/<path:_id>/',
         views.order_cs_child_add, name='order-cs-child-add'),
    path('cashin/', views.cashin_index, name='cashin-index'),
    path('cashin/add/<path:_id>/<str:_msg>/',
         views.cashin_add, name='cashin-add'),
    path('cashin/view/<int:_id>/', views.cashin_view, name='cashin-view'),
    path('cashin/update/<int:_id>/<str:_msg>/',
         views.cashin_update, name='cashin-update'),
    path('cashin/remove-evidence/<int:_id>/',
         views.remove_evidence, name='remove-evidence'),
    path('cashin/delete/<int:_id>/', views.cashin_delete, name='cashin-delete'),]
