# Generated by Django 5.0.6 on 2025-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_attendance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='address_in',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='address_out',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
