# Generated by Django 5.0.6 on 2025-01-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_task_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checklist_name', models.CharField(max_length=50)),
                ('checklist_status', models.BooleanField(default=False)),
                ('checklist_remark', models.CharField(max_length=200, null=True)),
                ('checklist_date', models.DateTimeField(null=True)),
                ('checklist_by', models.CharField(max_length=50, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.task')),
            ],
        ),
    ]
