# Generated by Django 5.0.6 on 2025-01-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_name',
        ),
    ]
