# Generated by Django 5.0.6 on 2025-01-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_checklist_checklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_status',
            field=models.CharField(default='Belum Dikerjakan', max_length=20),
        ),
    ]
