# Generated by Django 5.0.6 on 2025-01-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_checklist_checklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='checklist_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_start',
            field=models.DateTimeField(null=True),
        ),
    ]
