# Generated by Django 5.0.6 on 2025-01-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_checklist_checklist_end_checklist_checklist_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='checklist_duration',
            field=models.IntegerField(default=0),
        ),
    ]
