# Generated by Django 5.0.6 on 2025-01-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_checklist_checklist_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.room'),
        ),
    ]
