# Generated by Django 5.0.6 on 2025-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_checklist_checklist_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_duration',
            field=models.DateTimeField(null=True),
        ),
    ]
