# Generated by Django 5.0.6 on 2025-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_checklist_checklist_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_duration',
            field=models.IntegerField(default=0),
        ),
    ]
