# Generated by Django 5.0.6 on 2025-01-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_checklist_checklist_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_attachment',
            field=models.ImageField(null=True, upload_to='checklist/'),
        ),
    ]
