# Generated by Django 5.0.6 on 2025-01-13 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_checklist_checklist_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='janitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
