# Generated by Django 5.0.6 on 2025-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_room_janitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='checklist_priority',
            field=models.BooleanField(default=False),
        ),
    ]
