# Generated by Django 5.0.6 on 2025-02-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_checklist_checklist_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='checklist_priority',
            new_name='checklist_urgent',
        ),
    ]
