# Generated by Django 5.0.6 on 2025-02-10 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_rename_checklist_priority_checklist_checklist_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='janitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
