# Generated by Django 5.0.6 on 2025-02-11 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_region_janitor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='regiondetail',
            name='unique_region_area',
        ),
        migrations.RemoveField(
            model_name='regiondetail',
            name='area',
        ),
        migrations.AddField(
            model_name='regiondetail',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.room'),
        ),
        migrations.AddConstraint(
            model_name='regiondetail',
            constraint=models.UniqueConstraint(fields=('region', 'room'), name='unique_region_room'),
        ),
    ]
