# Generated by Django 5.0.6 on 2025-02-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_remove_regiondetail_unique_region_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='janitor',
        ),
    ]
