# Generated by Django 5.0.6 on 2025-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_remove_room_janitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='janitor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
