# Generated by Django 5.0.6 on 2025-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_checklist_janitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='thu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='wed',
            field=models.BooleanField(default=False),
        ),
    ]
