# Generated by Django 5.0.6 on 2025-09-02 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_task_fri_task_mon_task_sat_task_sun_task_thu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('absence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('absence_date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
