# Generated by Django 5.0.6 on 2025-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='absence_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
