# Generated by Django 5.0.6 on 2025-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_absence_absence_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='photo',
            field=models.ImageField(null=True, upload_to='attendance/'),
        ),
    ]
