# Generated by Django 5.0.6 on 2025-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_absence_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
