# Generated by Django 5.0.6 on 2025-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_absence_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='latitude',
            new_name='lat_in',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='longitude',
            new_name='lat_out',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='photo',
            new_name='photo_in',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='absence_time',
            new_name='time_in',
        ),
        migrations.AddField(
            model_name='absence',
            name='long_in',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='long_out',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='photo_out',
            field=models.ImageField(null=True, upload_to='attendance/'),
        ),
        migrations.AddField(
            model_name='absence',
            name='time_out',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
