# Generated by Django 5.0.6 on 2025-09-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_rename_latitude_absence_lat_in_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absence',
            new_name='Attendance',
        ),
    ]
