# Generated by Django 5.0.6 on 2025-09-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_rename_absence_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.TimeField(null=True),
        ),
    ]
