# Generated by Django 5.0.6 on 2025-09-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_attendance_time_in_alter_attendance_time_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.TimeField(null=True),
        ),
    ]
