# Generated by Django 5.0.6 on 2025-09-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_alter_attendance_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
