# Generated by Django 5.0.6 on 2025-09-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_alter_attendance_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.TimeField(null=True),
        ),
    ]
